// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SDPP.Documents.Infrastructure.Persistence;

#nullable disable

namespace SDPP.Documents.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DocumentsDbContext))]
    [Migration("20260731150721_AddDocumentIdentityAndFingerprint")]
    partial class AddDocumentIdentityAndFingerprint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("documents")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SDPP.BuildingBlocks.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", "documents");
                });

            modelBuilder.Entity("SDPP.Documents.Domain.Aggregates.ConversionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ApprovalRequired")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("int");

                    b.Property<string>("EngineUsed")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorDetail")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("OutputDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("ConversionJobs", "documents");
                });

            modelBuilder.Entity("SDPP.Documents.Domain.Aggregates.DocumentInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Classification")
                        .HasColumnType("tinyint");

                    b.Property<byte>("ClassificationSource")
                        .HasColumnType("tinyint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("ConvertedFromInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DocumentVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IntegritySignature")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Labels")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("ProtectionsApplied")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RiskScore")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("ConvertedFromInstanceId");

                    b.HasIndex("DocumentVersionId");

                    b.ToTable("DocumentInstances", "documents");
                });

            modelBuilder.Entity("SDPP.Documents.Domain.Aggregates.DocumentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangeTypeFromPrevious")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte>("Classification")
                        .HasColumnType("tinyint");

                    b.Property<byte>("ClassificationSource")
                        .HasColumnType("tinyint");

                    b.Property<string>("ContentFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("Labels")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LogicalDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PreviousVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("RiskScore")
                        .HasColumnType("int");

                    b.Property<string>("StructuralSignature")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContentFingerprint");

                    b.HasIndex("LogicalDocumentId");

                    b.HasIndex("LogicalDocumentId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("DocumentVersions", "documents");
                });

            modelBuilder.Entity("SDPP.Documents.Domain.Aggregates.LogicalDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CurrentVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("LogicalDocuments", "documents");
                });

            modelBuilder.Entity("SDPP.Documents.Domain.Aggregates.ConversionJob", b =>
                {
                    b.HasOne("SDPP.Documents.Domain.Aggregates.DocumentInstance", null)
                        .WithMany("Jobs")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SDPP.Documents.Domain.ValueObjects.ProcessingRequestForm", "Form", b1 =>
                        {
                            b1.Property<Guid>("ConversionJobId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Area")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Area");

                            b1.Property<string>("CaseNumber")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("CaseNumber");

                            b1.Property<string>("Client")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Client");

                            b1.Property<byte>("DeclaredClassification")
                                .HasColumnType("tinyint")
                                .HasColumnName("DeclaredClassification");

                            b1.Property<string>("Destination")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("Destination");

                            b1.Property<string>("Justification")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("Justification");

                            b1.Property<string>("Process")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Process");

                            b1.Property<string>("Project")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Project");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Reason");

                            b1.HasKey("ConversionJobId");

                            b1.ToTable("ProcessingRequestForms", "documents");

                            b1.WithOwner()
                                .HasForeignKey("ConversionJobId");

                            b1.OwnsOne("SDPP.Documents.Domain.ValueObjects.RetentionPeriod", "Retention", b2 =>
                                {
                                    b2.Property<Guid>("ProcessingRequestFormConversionJobId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<byte>("Action")
                                        .HasColumnType("tinyint")
                                        .HasColumnName("RetentionAction");

                                    b2.Property<int?>("Days")
                                        .HasColumnType("int")
                                        .HasColumnName("RetentionDays");

                                    b2.Property<bool>("IsPermanent")
                                        .HasColumnType("bit")
                                        .HasColumnName("RetentionIsPermanent");

                                    b2.HasKey("ProcessingRequestFormConversionJobId");

                                    b2.ToTable("ProcessingRequestForms", "documents");

                                    b2.WithOwner()
                                        .HasForeignKey("ProcessingRequestFormConversionJobId");
                                });

                            b1.Navigation("Retention")
                                .IsRequired();
                        });

                    b.Navigation("Form")
                        .IsRequired();
                });

            modelBuilder.Entity("SDPP.Documents.Domain.Aggregates.DocumentInstance", b =>
                {
                    b.OwnsOne("SDPP.Documents.Domain.ValueObjects.RetentionPeriod", "RetentionPolicy", b1 =>
                        {
                            b1.Property<Guid>("DocumentInstanceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte>("Action")
                                .HasColumnType("tinyint")
                                .HasColumnName("RetentionAction");

                            b1.Property<int?>("Days")
                                .HasColumnType("int")
                                .HasColumnName("RetentionDays");

                            b1.Property<bool>("IsPermanent")
                                .HasColumnType("bit")
                                .HasColumnName("RetentionIsPermanent");

                            b1.HasKey("DocumentInstanceId");

                            b1.ToTable("DocumentInstances", "documents");

                            b1.WithOwner()
                                .HasForeignKey("DocumentInstanceId");
                        });

                    b.OwnsOne("SDPP.Documents.Domain.ValueObjects.FileHash", "Sha256Hash", b1 =>
                        {
                            b1.Property<Guid>("DocumentInstanceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("Sha256Hash");

                            b1.HasKey("DocumentInstanceId");

                            b1.HasIndex("Value");

                            b1.ToTable("DocumentInstances", "documents");

                            b1.WithOwner()
                                .HasForeignKey("DocumentInstanceId");
                        });

                    b.OwnsOne("SDPP.Documents.Domain.ValueObjects.StoragePath", "StorageLocation", b1 =>
                        {
                            b1.Property<Guid>("DocumentInstanceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Bucket")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("StorageBucket");

                            b1.Property<string>("ObjectKey")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasColumnName("StorageObjectKey");

                            b1.HasKey("DocumentInstanceId");

                            b1.ToTable("DocumentInstances", "documents");

                            b1.WithOwner()
                                .HasForeignKey("DocumentInstanceId");
                        });

                    b.Navigation("RetentionPolicy");

                    b.Navigation("Sha256Hash")
                        .IsRequired();

                    b.Navigation("StorageLocation")
                        .IsRequired();
                });

            modelBuilder.Entity("SDPP.Documents.Domain.Aggregates.DocumentInstance", b =>
                {
                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
