// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SDPP.Classification.Infrastructure.Persistence;

#nullable disable

namespace SDPP.Classification.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ClassificationDbContext))]
    [Migration("20260727001621_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("classification")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SDPP.BuildingBlocks.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", "classification");
                });

            modelBuilder.Entity("SDPP.Classification.Domain.Aggregates.ClassificationPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ScopeValue")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ClassificationPolicies", "classification");
                });

            modelBuilder.Entity("SDPP.Classification.Domain.Aggregates.DlpRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte>("DefaultSeverity")
                        .HasColumnType("tinyint");

                    b.Property<string>("DetectorType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PatternOrConfigJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DlpRules", "classification");
                });

            modelBuilder.Entity("SDPP.Classification.Domain.Aggregates.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DetectorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("InspectionResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MatchCount")
                        .HasColumnType("int");

                    b.Property<string>("RuleVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("Severity")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("InspectionResultId");

                    b.ToTable("Findings", "classification");
                });

            modelBuilder.Entity("SDPP.Classification.Domain.Aggregates.InspectionResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("FinalClassification")
                        .HasColumnType("tinyint");

                    b.Property<bool>("RequiresManualReview")
                        .HasColumnType("bit");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<byte>("SuggestedClassification")
                        .HasColumnType("tinyint");

                    b.Property<byte>("TriggeredBy")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("InspectionResults", "classification");
                });

            modelBuilder.Entity("SDPP.Classification.Domain.Aggregates.PolicyRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClassificationPolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConditionAreaEquals")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte?>("ConditionClassification")
                        .HasColumnType("tinyint");

                    b.Property<string>("ConditionOperationType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassificationPolicyId");

                    b.ToTable("PolicyRules", "classification");
                });

            modelBuilder.Entity("SDPP.Classification.Domain.Aggregates.Finding", b =>
                {
                    b.HasOne("SDPP.Classification.Domain.Aggregates.InspectionResult", null)
                        .WithMany("Findings")
                        .HasForeignKey("InspectionResultId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SDPP.Classification.Domain.Aggregates.PolicyRule", b =>
                {
                    b.HasOne("SDPP.Classification.Domain.Aggregates.ClassificationPolicy", null)
                        .WithMany("Rules")
                        .HasForeignKey("ClassificationPolicyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SDPP.Classification.Domain.Aggregates.ClassificationPolicy", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("SDPP.Classification.Domain.Aggregates.InspectionResult", b =>
                {
                    b.Navigation("Findings");
                });
#pragma warning restore 612, 618
        }
    }
}
