// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SDPP.Classification.Infrastructure.Persistence;

#nullable disable

namespace SDPP.Classification.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ClassificationDbContext))]
    [Migration("20260731203913_AddIntegrityAndFingerprintTables")]
    partial class AddIntegrityAndFingerprintTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("classification")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SDPP.BuildingBlocks.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", "classification");
                });

            modelBuilder.Entity("SDPP.Classification.Domain.Aggregates.ClassificationPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ScopeValue")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ClassificationPolicies", "classification");
                });

            modelBuilder.Entity("SDPP.Classification.Domain.Aggregates.DlpRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessCategory")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte>("DefaultSeverity")
                        .HasColumnType("tinyint");

                    b.Property<string>("DetectorType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Labels")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PatternOrConfigJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DlpRules", "classification");
                });

            modelBuilder.Entity("SDPP.Classification.Domain.Aggregates.DocumentIntegrityRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DocumentVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IntegritySignature")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProtectionsApplied")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.HasIndex("DocumentVersionId");

                    b.ToTable("DocumentIntegrityRecords", "classification");
                });

            modelBuilder.Entity("SDPP.Classification.Domain.Aggregates.DocumentVersionFingerprint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Classification")
                        .HasColumnType("tinyint");

                    b.Property<byte>("ClassificationSource")
                        .HasColumnType("tinyint");

                    b.Property<string>("ContentFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Labels")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("LogicalDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("RiskScore")
                        .HasColumnType("int");

                    b.Property<string>("StructuralSignature")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContentFingerprint");

                    b.HasIndex("DocumentVersionId")
                        .IsUnique();

                    b.HasIndex("LogicalDocumentId");

                    b.ToTable("DocumentVersionFingerprints", "classification");
                });

            modelBuilder.Entity("SDPP.Classification.Domain.Aggregates.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessCategory")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DetectorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("InspectionResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Labels")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MatchCount")
                        .HasColumnType("int");

                    b.Property<string>("RuleVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("Severity")
                        .HasColumnType("tinyint");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InspectionResultId");

                    b.ToTable("Findings", "classification");
                });

            modelBuilder.Entity("SDPP.Classification.Domain.Aggregates.InspectionResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessCategory")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("FinalClassification")
                        .HasColumnType("tinyint");

                    b.Property<string>("Labels")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("RequiresManualReview")
                        .HasColumnType("bit");

                    b.Property<int>("RiskScore")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<byte>("SuggestedClassification")
                        .HasColumnType("tinyint");

                    b.Property<byte>("TriggeredBy")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("InspectionResults", "classification");
                });

            modelBuilder.Entity("SDPP.Classification.Domain.Aggregates.PolicyRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClassificationPolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConditionAreaEquals")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ConditionCategory")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte?>("ConditionClassification")
                        .HasColumnType("tinyint");

                    b.Property<string>("ConditionOperationType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassificationPolicyId");

                    b.ToTable("PolicyRules", "classification");
                });

            modelBuilder.Entity("SDPP.Classification.Domain.Aggregates.DocumentIntegrityRecord", b =>
                {
                    b.OwnsOne("SDPP.Classification.Domain.ValueObjects.FileHash", "Sha256Hash", b1 =>
                        {
                            b1.Property<Guid>("DocumentIntegrityRecordId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("Sha256Hash");

                            b1.HasKey("DocumentIntegrityRecordId");

                            b1.HasIndex("Value");

                            b1.ToTable("DocumentIntegrityRecords", "classification");

                            b1.WithOwner()
                                .HasForeignKey("DocumentIntegrityRecordId");
                        });

                    b.Navigation("Sha256Hash")
                        .IsRequired();
                });

            modelBuilder.Entity("SDPP.Classification.Domain.Aggregates.Finding", b =>
                {
                    b.HasOne("SDPP.Classification.Domain.Aggregates.InspectionResult", null)
                        .WithMany("Findings")
                        .HasForeignKey("InspectionResultId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SDPP.Classification.Domain.Aggregates.PolicyRule", b =>
                {
                    b.HasOne("SDPP.Classification.Domain.Aggregates.ClassificationPolicy", null)
                        .WithMany("Rules")
                        .HasForeignKey("ClassificationPolicyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SDPP.Classification.Domain.Aggregates.ClassificationPolicy", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("SDPP.Classification.Domain.Aggregates.InspectionResult", b =>
                {
                    b.Navigation("Findings");
                });
#pragma warning restore 612, 618
        }
    }
}
